#!/bin/bash
# export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
# won't work.
# has to be done using rhc env set, see http://stackoverflow.com/questions/35688756/openshift-diy-cartridige-with-tomcat-8-and-jdk-8-javahome-subscribe
# like this: rhc env set JAVA_HOME=/etc/alternatives/java_sdk_1.8.0 -a diy

mvn_version=3.3.9
echo "build hook"
#export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
#export PATH=$JAVA_HOME/bin:$PATH

export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"

echo $(java -version)

# but then also this had to be considered http://stackoverflow.com/questions/23894323/jdk-8-support-at-diy-cartridge-in-openshift

cd $OPENSHIFT_DATA_DIR
echo -e  "<settings>\n <localRepository>$OPENSHIFT_DATA_DIR/.m2/</localRepository>\n</settings>\n" > settings.xml

$OPENSHIFT_DATA_DIR/apache-maven-$mvn_version/bin/mvn -f $OPENSHIFT_REPO_DIR/pom.xml clean package -s $OPENSHIFT_DATA_DIR/settings.xml

#mvn package -s .openshift/settings.xml -DskipTests=true
