#!/bin/bash
cd $OPENSHIFT_DATA_DIR
version=3.3.9

#Download Maven If not already installed
#if [ ! -d apache-maven-$version ]; then
#  echo "downloading apache-maven-$version"
#  wget http://www.eu.apache.org/dist/maven/maven-3/$version/binaries/apache-maven-$version-bin.tar.gz
#  tar -zxf apache-maven-$version-bin.tar.gz
#fi

m2dir=~/app-root/data/.m2

if [ ! -d $m2dir ]; then
	echo "creating $m2dir"
	mkdir $m2dir
fi

rm $m2dir/tooolchains.xml

cat > $m2dir/tooolchains.xml <<End-of-message
<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">
 <!-- JDK toolchains -->
 <toolchain>
   <type>jdk</type>
   <provides>
     <version>1.15</version>
     <vendor>sun</vendor>
   </provides>
   <configuration>
     <jdkHome>/etc/alternatives/java_sdk_1.7.0</jdkHome>
   </configuration>
 </toolchain>
 <toolchain>
   <type>jdk</type>
   <provides>
     <version>1.16</version>
     <vendor>sun</vendor>
   </provides>
   <configuration>
     <jdkHome>/etc/alternatives/java_sdk_1.7.0</jdkHome>
   </configuration>
 </toolchain>
 <toolchain>
   <type>jdk</type>
   <provides>
     <version>1.17</version>
     <vendor>sun</vendor>
   </provides>
   <configuration>
     <jdkHome>/etc/alternatives/java_sdk_1.7.0</jdkHome>
   </configuration>
 </toolchain>
 <toolchain>
   <type>jdk</type>
   <provides>
     <version>1.8</version>
     <vendor>sun</vendor>
   </provides>
   <configuration>
     <jdkHome>/etc/alternatives/java_sdk_1.8.0</jdkHome>
   </configuration>
 </toolchain>
</toolchains>
End-of-message


