#!/bin/bash
cd $OPENSHIFT_DATA_DIR
version=3.3.9

#Download Maven If not already installed
if [ ! -d apache-maven-$version ]; then
  echo "downloading apache-maven-$version"
  wget http://www.eu.apache.org/dist/maven/maven-3/$version/binaries/apache-maven-$version-bin.tar.gz
  tar -zxf apache-maven-$version-bin.tar.gz
fi

#Download Java8 If not already installed
if [ ! -d jdk1.8.0_05 ]; then
  if [ ! -e jdk-8u5-linux-x64.tar.gz ]; then	
  echo "downloading jdk1.8.0_05"
  	wget --no-check-certificate --no-cookies --header "Cookie:    oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
  fi
  tar -zxf jdk-8u5-linux-x64.tar.gz
fi
