#!/bin/bash

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

echo $(java -version)

cd $OPENSHIFT_REPO_DIR
echo "main class can't be found? main class name changed, but not mainClass - maven-jar-plugin in pom?"
nohup java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -jar adscraperApp/target/adscraperapp-0.1.0.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP}

