#!/bin/bash

echo "start hook"
#export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
#export PATH=$JAVA_HOME/bin:$PATH

export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"

echo $(java -version)

cd $OPENSHIFT_REPO_DIR
nohup java -jar app/target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
